name: 'Run Script'
description: 'Action to run a bash script'

inputs:
  script:
    description: 'The script to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

      
    - name: 'Run Script'
      run: |
        ${{ inputs.script }}
