name: 'Run Script'
description: 'Action to run a bash script'

inputs:
  script:
    description: 'The script to run'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Run Script'
      shell: bash  # Set the shell for this specific run step
      run: |
        ${{ inputs.script }}
