name: Run Workflow
on:
  workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: 'Run Script'
        uses: ./action.yml
        with:
          script: |
            echo "Hello, World!"
            echo "This is a bash script."
